"""updated transactions table

Revision ID: 04385051275a
Revises: 224b617ad210
Create Date: 2021-04-07 22:44:58.177397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04385051275a'
down_revision = '224b617ad210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_transactions', sa.Column('expense_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_transactions', 'expenses', ['expense_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_transactions', type_='foreignkey')
    op.drop_column('user_transactions', 'expense_id')
    # ### end Alembic commands ###
