"""add hash column in user table

Revision ID: 53c1299945b7
Revises: 04385051275a
Create Date: 2021-04-07 23:36:32.232185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c1299945b7'
down_revision = '04385051275a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hash')
    # ### end Alembic commands ###
